### ISSUE TITLE
Does not work with module loader for browser

### ISSUE THREAD

**Issue by kuechlerm** [asciidoctor/asciidoctor.js#178]
When using JSPM or Webpack, requiring / importing asciidoctor.js requires the node module "fs".
This does not work, because I want to use it in a browser environment.
When my code runs, the right path (caused by JAVASCRIPT_PLATFORM) is used. But for reasons unknown both JSPM and Webpack tell me that they cannot find the module "fs".

Can you provide a package with browser-only code and please please publish it on npm?
Or is already something out there? Or a setting I miss? 
Thanks.

**Comment by anthonny** [comment]
Hi @kuechlerm 

I have the same problem with HubPress and i'm working on it.
I use babel/browserify and with this tools JAVASCRIPT_PLATFORM is considered as 'node' instead of 'browser'.
This is because in this kind of "compilation" the test `(typeof module !== 'undefined' && module.exports)` return `true` 
https://github.com/asciidoctor/asciidoctor.js/blob/master/lib/asciidoctor/opal_ext.rb#L3

I have changed the test: 
https://github.com/anthonny/asciidoctor.js/blob/master/lib/asciidoctor/opal_ext.rb#L3

Now the JAVASCRIPT_PLATFORM is correct but i still have an issue with `include::[]`: 
`TypeError: Cannot read property 'write' of undefined at $IO.write_proc`

But i'm sure that @Mogztter or @mojavelinux will help us ;)

**Comment by kuechlerm** [comment]
:+1: @anthonny

**Comment by Mogztter** [comment]
Interesting.
@anthonny Could you please open a pull request with your fix on `opal_ext` ?

> Now the JAVASCRIPT_PLATFORM is correct but i still have an issue with include::[]: 
TypeError: Cannot read property 'write' of undefined at $IO.write_proc

Do you have a simple test to reproduce the problem ? 

Thanks

**Comment by anthonny** [comment]
Yes i will open a PR i must rebase before.
I do not have a simple test, i encounter this error during the development of HubPress
But i suppose that i can create a little project to reproduce.

**Comment by anthonny** [comment]
The PR is here https://github.com/asciidoctor/asciidoctor.js/pull/179

**Comment by anthonny** [comment]
@kuechlerm we are working on this problem, we are waiting for the 0.9.2 in the opal-cdn project.
You can already use the fixed version and make some tests by using my repository:
`"asciidoctor.js": "github:anthonny/asciidoctor.js#fix-opal"`

**Comment by kuechlerm** [comment]
@anthonny I tried bundling with webpack but got this errrors:

```
ERROR in ./~/asciidoctor.js/dist/npm/asciidoctor-core.min.js
Module not found: Error: Cannot resolve module 'fs' in [...]\node_modules\asciidoctor.js\dist\npm
 @ ./~/asciidoctor.js/dist/npm/asciidoctor-core.min.js 26:223-236

ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'fs' in [...]\node_modules\xmlhttprequest\lib
 @ ./~/xmlhttprequest/lib/XMLHttpRequest.js 16:9-22

ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'child_process' in [...]\node_modules\xmlhttprequest\lib
 @ ./~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36
```

**Comment by anthonny** [comment]
Yes i had a similar issue, xmlhttprequest seems to not work with module loader for browser

Here is how i use asciidoctor with browserify:
```js
import asciiDoctorLib from 'asciidoctor.js';
const asciidoctor = asciiDoctorLib(false, window.XMLHttpRequest); // I force to use window.XMLHttpRequest
const opal = asciidoctor.Opal;
const processor = asciidoctor.Asciidoctor(true);
```

**Comment by Mogztter** [comment]
@anthonny Is it possible to do it automatically if we detect that we are running in a "Browserify environment" ?

**Comment by Mogztter** [comment]
Should be resolved by #248

**Comment by Mogztter** [comment]
I've added a test case with Webpack: #258

**Comment by Mogztter** [comment]
I believe this issue is now resolved.
If that's not the case in your context, feel free to open a new issue.

**Comment by ShankarSumanth** [comment]
So what's the process now to use it with es6 imports and webpack? I still get 

`ERROR in ./~/asciidoctor.js/dist/asciidoctor.js
Module not found: Error: Can't resolve 'fs'` error. 

I am simply trying to use 
`import { ascidoctor } from 'asciidoctor.js';` in an angular 4 webpack project

**Comment by Mogztter** [comment]
You shouldn't need `fs` module.
The `asciidoctor.js` contains both the implementation to read files in Node (module `fs`) and the browser (`XMLHttpRequest`).

Could you please try to add the following configuration in your Webpack configuration: https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285600014

**Comment by Mogztter** [comment]
There's an open issue to decide if we should publish a dedicate file per environment or not: https://github.com/asciidoctor/asciidoctor.js/issues/396
